"""Enhance AnalysisResult model

Revision ID: 371c9224ecc9
Revises: a2089f9acd1d
Create Date: 2024-11-27 01:19:31.227200

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '371c9224ecc9'
down_revision: Union[str, None] = 'a2089f9acd1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
