"""Add assistant, tool, conversation, message, run models

Revision ID: 493e7727f4fd
Revises: 1007ec58dfb7
Create Date: 2024-12-02 19:09:13.994533

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "493e7727f4fd"
down_revision: Union[str, None] = "1007ec58dfb7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "conversations", sa.Column("analysis_id", sa.Integer(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("conversations", "analysis_id")
    # ### end Alembic commands ###
